-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 16:04:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_fund` YEAR(4) NOT NULL,
  `fat_ano_ant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tempo_prod` VARCHAR(45) NOT NULL,
  `ano_lanc` YEAR(4) NOT NULL,
  `numCopyright` VARCHAR(45) NOT NULL,
  `custo` VARCHAR(45) NOT NULL,
  `Estudio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Estudio_id`),
  INDEX `fk_Filme_Estudio1_idx` (`Estudio_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Filme_Estudio1`
    FOREIGN KEY (`Estudio_id`)
    REFERENCES `mydb`.`Estudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(45) NOT NULL,
  `Pais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pais_id`),
  INDEX `fk_Uf_Pais1_idx` (`Pais_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Uf_Pais1`
    FOREIGN KEY (`Pais_id`)
    REFERENCES `mydb`.`Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NOT NULL,
  `Uf_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Uf_id`),
  INDEX `fk_Cidade_Uf1_idx` (`Uf_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Uf1`
    FOREIGN KEY (`Uf_id`)
    REFERENCES `mydb`.`Uf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Naturalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Naturalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cidade_id`),
  INDEX `fk_Naturalidade_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Naturalidade_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoCivil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_civ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quadra` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cidade_id`),
  INDEX `fk_Endereço_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filiacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pai` VARCHAR(45) NULL,
  `mae` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `identidade` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Naturalidade_id` INT NOT NULL,
  `Sexo_id` INT NOT NULL,
  `Escolaridade_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pessoa_Naturalidade_idx` (`Naturalidade_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_Escolaridade1_idx` (`Escolaridade_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_Estado Civil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_Endereço1_idx` (`Endereco_id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `identidade_UNIQUE` (`identidade` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Pessoa_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Naturalidade`
    FOREIGN KEY (`Naturalidade_id`)
    REFERENCES `mydb`.`Naturalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Escolaridade1`
    FOREIGN KEY (`Escolaridade_id`)
    REFERENCES `mydb`.`Escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Estado Civil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Endereço1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_artistico` VARCHAR(45) NOT NULL,
  `num_seg_social` VARCHAR(45) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pessoa_id`),
  INDEX `fk_Ator_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  UNIQUE INDEX `num_seg_social_UNIQUE` (`num_seg_social` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Ator_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diretor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_artistico` VARCHAR(45) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  `Filme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pessoa_id`, `Filme_id`),
  INDEX `fk_Diretor_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_Diretor_Filme1_idx` (`Filme_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Diretor_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diretor_Filme1`
    FOREIGN KEY (`Filme_id`)
    REFERENCES `mydb`.`Filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Ator_id` INT NOT NULL,
  `Filme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Ator_id`, `Filme_id`),
  INDEX `fk_Personagem_Ator1_idx` (`Ator_id` ASC) VISIBLE,
  INDEX `fk_Personagem_Filme1_idx` (`Filme_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Personagem_Ator1`
    FOREIGN KEY (`Ator_id`)
    REFERENCES `mydb`.`Ator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_Filme1`
    FOREIGN KEY (`Filme_id`)
    REFERENCES `mydb`.`Filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DonoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DonoEstudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Estudio_id` INT NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Estudio_id`, `Pessoa_id`),
  INDEX `fk_DonoEstudio_Estudio1_idx` (`Estudio_id` ASC) VISIBLE,
  INDEX `fk_DonoEstudio_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_DonoEstudio_Estudio1`
    FOREIGN KEY (`Estudio_id`)
    REFERENCES `mydb`.`Estudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DonoEstudio_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `Filme_id` INT NOT NULL AUTO_INCREMENT,
  `Ator_id` INT NOT NULL,
  `cache` INT NOT NULL,
  PRIMARY KEY (`Filme_id`, `Ator_id`),
  INDEX `fk_Filme_has_Ator_Ator1_idx` (`Ator_id` ASC) VISIBLE,
  INDEX `fk_Filme_has_Ator_Filme1_idx` (`Filme_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filme_has_Ator_Filme1`
    FOREIGN KEY (`Filme_id`)
    REFERENCES `mydb`.`Filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_has_Ator_Ator1`
    FOREIGN KEY (`Ator_id`)
    REFERENCES `mydb`.`Ator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Papel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(300) NULL,
  `Ator_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Ator_id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE,
  INDEX `fk_Papel_Ator1_idx` (`Ator_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Papel_Ator1`
    FOREIGN KEY (`Ator_id`)
    REFERENCES `mydb`.`Ator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefone_Pessoa2_idx` (`Pessoa_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa2`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefone_Pessoa2_idx` (`Pessoa_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa2`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
